### ISSUE TITLE
fails to evaluate when electron-webrtc is called from main.js

### ISSUE THREAD

**Issue by arcman7** [mappum/electron-webrtc#39]
App threw an error when running [SyntaxError: /Users/Desktop/sound-machine-electron-guide/node_modules/electron-webrtc/src/RTCPeerConnection.js:10
  daemon.eval('window.conns = {}', (err) => {
                                       ^
missing ) after argument list]

**Comment by mappum** [comment]
@arcman77 What version of node are you using?

**Comment by arcman77** [comment]
version 5.5.0

Just a thought, but could my error possibly have something to do me using a prebuilt electron binary -     "electron-prebuilt": "^0.30.3" ?

**Comment by mappum** [comment]
Yeah, I bet that's it. Could you try making sure `electron-prebuilt` is at `0.37.x`?

**Comment by arcman7** [comment]
kk, I'll let you know what happens

**Comment by danzel** [comment]
@arcman7 did it work?

**Comment by arcman7** [comment]
@mappum, @danzel yes it did, sorry for the 9-month delay.

**Comment by danzel** [comment]
Haha :)
Close this then issue please
