### ISSUE TITLE
No response after calling RTCPerrConnection.createOffer

### ISSUE THREAD

**Issue by yciabaud** [mappum/electron-webrtc#52]
Some users of webtorrent-hybrid reported problems using webrtc on a headless server.

I am able to reproduce the issue on Ubuntu Server 14.04.4 LTS 64bit deployed on Amazon EC2 instance (xvfb installed).

We are calling `RTCPerrConnection.createOffer` and neither the success or the error callback is triggered.

Do you have an idea on how to debug this issue?

**Comment by yciabaud** [comment]
FYI we have seen similar issues on different virtualized envs (digital ocean, virtual box...) all under ubuntu server but we havent tested other distros yet.

**Comment by yciabaud** [comment]
Looks like this problem occurs when some chrome deps are not installed on the system.

`apt-get install -y libgtk2.0-0 libgconf-2-4 libasound2 libxtst6 libxss1 libnss3 xvfb` seems to fix this.

**Comment by yciabaud** [comment]
I dont know if you have seen my mesages on webtorrent chat but the fixes from offer-answer-fixes are working for this issue. Feel free to merge it ;)

**Comment by mappum** [comment]
@yciabaud Awesome! :+1: I did publish the changes, you should be able to reinstall your deps
